services:
  - type: web
    name: gestdepense-api
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://gestdepense-api.onrender.com
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: gestdepense-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: SANCTUM_STATEFUL_DOMAINS
        sync: false
      - key: FRONTEND_URL
        sync: false

databases:
  - name: gestdepense-db
    region: oregon
    plan: free
    databaseName: gestdepense
    user: gestdepense
